#!/bin/sh

# Copyright 2020-2021 Ping Identity Corporation
# All Rights Reserved.
#
# -----
#
# Copyright 2020-2021 Ping Identity Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# -----
#
# Copyright (C) 2020-2021 Ping Identity Corporation
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPLv2 only)
# as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License


# Get the current working directory and the tools directory.
CURRENT_DIR=`pwd`
cd "`dirname "${0}"`"
TOOLS_DIR=`pwd`
cd ${CURRENT_DIR}


# Invoke a number of common script utility functions.
. "${TOOLS_DIR}/.script-util.sh"


# Invoke the tool with the provided command-line arguments.
"${JAVA_CMD}" ${JAVA_ARGS} -cp "${TOOLS_DIR}/../unboundid-ldapsdk.jar" \
     com.unboundid.ldap.sdk.unboundidds.tools.CollectSupportData "${@}"

