/*
 * Copyright 2009-2016 UnboundID Corp.
 * All Rights Reserved.
 */
/*
 * Copyright (C) 2015-2016 UnboundID Corp.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License (GPLv2 only)
 * or the terms of the GNU Lesser General Public License (LGPLv2.1 only)
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 */



/**
 * <BLOCKQUOTE>
 *   <B>NOTE:</B>  This package is part of the Commercial Edition of the
 *   UnboundID LDAP SDK for Java.  It is not available for use in applications
 *   that include only the Standard Edition of the LDAP SDK, and is not
 *   supported for use in conjunction with non-UnboundID products.
 * </BLOCKQUOTE>
 * This package provides classes that may be used to parse access and error log
 * files generated by the UnboundID Directory Server.
 */
package com.unboundid.ldap.sdk.unboundidds.logs;
